name: EventsPlugin
version: @version@
main: uk.co.breadhub.events.Main
load: STARTUP
authors: [slicedbread]

commands:
  event:
    description: "Events Main Command"
    aliases:
      - "events"
      - "eventsadmin"
      - "eventadmin"