name: EventsPlugin
version: @version@
main: uk.co.breadhub.events.Main
api-version: 1.15
load: STARTUP
depend:
  - ProtocolLib
authors: [slicedbread]

commands:
  events:
    description: "Events Main Command"
    aliases:
      - "events"
      - "eventsadmin"